Name = str (input (f"Enter your name:+{"Father Name"} "))
per = int(input("Enter your percentage: "))

if per > 90:
    print(f"Wow, {Name} You achive 90%.!")
elif per > 80:
    print(f" {Name}! You achive 80%.")
elif per > 70:
    print(f" {Name}! You achive 70%")
elif per > 60:
    print(f" {Name}! You achive 60%")
elif per > 50:
    print(f" {Name}! You achive 50%")
elif per > 40:
    print(f" {Name}! You achive 40%")
elif per > 30:
    print(f" {Name}! You achive 30%")
else:
    print(f" {Name} You achive {per} Keep Hard work to do")
